name: RpcView Build
on: workflow_dispatch

jobs:
  RpcView-x86:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.4'
          architecture: 'x64'
      - name: Install Qt 5.15.2
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.15.2
          host: windows
          target: desktop
          arch: win32_msvc2019
      - name: Build RpcView-x86
        shell: pwsh
        run: |
          mkdir build\x86
          cd build\x86
          cmake -A Win32 -G "Visual Studio 17 2022" "-DCMAKE_PREFIX_PATH=${{ runner.workspace }}\Qt\5.15.2\msvc2019".Replace('\', '/') ..\..
          cmake --build . --config Release
          ${{ runner.workspace }}\Qt\5.15.2\msvc2019\bin\windeployqt.exe .\bin\Release\RpcView.exe
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: RpcView-x86.zip
          path: ${{ runner.workspace }}\RpcView\build\x86\bin\Release

  RpcView-x64:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.4'
          architecture: 'x64'
      - name: Install Qt 5.15.2
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.15.2
          host: windows
          target: desktop
          arch: win64_msvc2019_64
      - name: Build RpcView-x64
        shell: pwsh
        run: |
          mkdir build\x64
          cd build\x64
          cmake -A x64 -G"Visual Studio 17 2022" "-DCMAKE_PREFIX_PATH=${{ runner.workspace }}\Qt\5.15.2\msvc2019_64".Replace('\', '/') ..\..
          cmake --build . --config Release
          ${{ runner.workspace }}\Qt\5.15.2\msvc2019_64\bin\windeployqt.exe .\bin\Release\RpcView.exe
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: RpcView-x64.zip
          path: ${{ runner.workspace }}\RpcView\build\x64\bin\Release
